apiVersion: v1
kind: ConfigMap
metadata:
  name: event-bridge-manager-config
data:
  EVENT_BRIDGE_DB_USERNAME: "postgres"
  EVENT_BRIDGE_DB_PASSWORD: "postgres"
  EVENT_BRIDGE_DB_HOST: "event-bridge-db"
  EVENT_BRIDGE_DB_PORT: "5432"
  EVENT_BRIDGE_DB_SCHEMA: "event-bridge"
  EVENT_BRIDGE_SSO_URL: "http://<REPLACE_WITH_MINIKUBE_IP>:30007/auth/realms/event-bridge-fm"
  EVENT_BRIDGE_SSO_CLIENT_ID: "event-bridge"
  AWS_ENDPOINT: "http://localstack.localstack:4566"
  AWS_ACCESS_KEY_ID: "test-key"
  AWS_SECRET_ACCESS_KEY: "test-secret"
  AWS_REGION: "us-west-1"
  SHARD_ID: "150b23e9-0b34-45b7-a91a-5ec388d03a1d"
  EVENT_BRIDGE_K8S_ORCHESTRATOR: "minikube"
  EVENT_BRIDGE_DNS_SUBDOMAIN_TLS_CERTIFICATE: ""          # Empty for minikube and kind
  EVENT_BRIDGE_DNS_SUBDOMAIN_TLS_KEY: ""                  # Empty for minikube and kind
  EVENT_BRIDGE_DNS_INGRESS_OVERRIDE_HOSTNAME: "<REPLACE_WITH_KIND_HOST_IF_ENABLED>"
  SHARD_ROUTER_CANONICAL_HOSTNAME: "default"
