images:
- name: event-bridge-manager
  newName: quay.io/5733d9e2be6485d52ffa08870cabdee0/fleet-manager
  newTag: ea43387478771bc409ca21ac2b5f492118770f06-jvm
- name: event-bridge-shard-operator
  newName: quay.io/5733d9e2be6485d52ffa08870cabdee0/fleet-shard
  newTag: ocp-ea43387478771bc409ca21ac2b5f492118770f06-jvm
patchesStrategicMerge:
- manager/patches/deploy.yaml
- manager/patches/deploy-config.yaml
- manager/patches/postgres-config.yaml
- shard/patches/deploy-config.yaml
resources:
- ../base
- manager
- shard
- observability
