apiVersion: kustomize.config.k8s.io/v1beta1
images:
- name: event-bridge-shard-operator
  newName: quay.io/5733d9e2be6485d52ffa08870cabdee0/fleet-shard
  newTag: ocp-045f4177e809643df4fd65cbbb4a5e856dedfc70-jvm
kind: Kustomization
namespace: event-bridge-prod
patchesJson6902:
- path: patch-with-knative-eventing-namespace.yaml
  target:
    group: ''
    kind: NetworkPolicy
    name: kafka-broker-receiver
    version: v1
- path: patch-with-knative-eventing-namespace.yaml
  target:
    group: ''
    kind: KnativeEventing
    name: knative-eventing
    version: v1alpha1
- path: patch-with-knative-eventing-namespace.yaml
  target:
    group: ''
    kind: KnativeKafka
    name: knative-kafka
    version: v1alpha1
- path: patch-with-knative-eventing-namespace.yaml
  target:
    group: ''
    kind: NetworkPolicy
    name: eventing-webhook
    version: v1
- path: patch-with-knative-eventing-namespace.yaml
  target:
    group: ''
    kind: NetworkPolicy
    name: kafka-webhook-eventing
    version: v1
- path: patch-with-knative-eventing-namespace.yaml
  target:
    group: ''
    kind: Gateway
    name: broker-gateway
    version: v1alpha3
- path: patch-with-istio-system-namespace.yaml
  target:
    group: ''
    kind: RequestAuthentication
    name: jwt-rh-sso
    version: v1beta1
- path: patch-with-istio-system-namespace.yaml
  target:
    group: ''
    kind: ServiceMeshControlPlane
    name: basic
    version: v2
- path: patch-with-istio-system-namespace.yaml
  target:
    group: ''
    kind: ServiceMeshMemberRoll
    name: default
    version: v1
- path: patch-with-knative-eventing-namespace.yaml
  target:
    group: ''
    kind: VirtualService
    name: broker-virtual-service
    version: v1alpha3
patchesStrategicMerge:
- patches/deploy-config.yaml
resources:
- ../../base/shard
- ../../base-openshift/shard
- namespace.yaml
- secrets
- shard
- awssm-secret.yaml
