patchesStrategicMerge:
- patches/deploy-config.yaml
namespace: event-bridge-operator
resources:
- namespace.yaml
- cluster-role.yaml
- cluster-role-binding.yaml
- addon-smart-events-operator-parameters.yaml
- ../../../base/shard